### ISSUE TITLE
Decompiling option problem

### ISSUE THREAD

**Issue by kleenexfeu** [cosarara97/red-alien#4]
Hello,
I'm using the latest windows build (23-01-2017), so I tried the command prompt version, and the gui version
The command version has option for decompiling move script and AI scripts, but these features don't seem to work. For the move scripting, it just gives raw bytes even with --moves, while the AI scripts can't get decompiled, the program freezes.
The gui version only seems to have the AI script decompiling feature (and the OW script too, but I'm not using that for now), but again, when using it, the program freezes.
Any clue on what's happening?

**Comment by cosarara** [comment]
Thanks for the report. Both should be fixed as of https://github.com/cosarara97/red-alien/commit/87e1514c2c9f6120d04b040817f518c604eafdbb .
I'll make a new release when I have the time.

**Comment by cosarara** [comment]
I made a new build http://www.cosarara.me/jaume/files/RedAlien_nightly_2017-08-08.zip
Please tell me how it goes if you try it out.

**Comment by kleenexfeu** [comment]
Thanks for the fix! I can't try it out rn but be sure I will get back to you as soon as I have enough time!
