### ISSUE TITLE
Running on Debian/Ubuntu

### ISSUE THREAD

**Issue by Roboe** [cosarara97/red-alien#5]
Not an issue, just providing some instructions for anyone running red-alien on Debian-based distros.

OS: Debian testing (buster)
Packaged dependencies:
 - `python3`
 - `python3-pyqt5` (depends on `python3`)
 - `python3-pyqt5.qsci` (depends on `python3-pyqt5`)

Minimum command to install dependencies: `sudo apt install python3-pyqt5.qsci`

Dependencies could be listed in a table in the readme file if you like:

Dependency | Arch package | Debian/Ubuntu package
--- | --- | ---
Python 3 | `python` | `python3`
PyQt 5 | `python-pyqt5` | `python3-pyqt5`<br>(depends on `python3`)
Python bindings for Qscintilla | `python-qscintilla-qt5` | `python3-pyqt5.qsci`<br>(depends on `python3-pyqt5`)

**Comment by cosarara** [comment]
Thank you! If you send a pull request to add it to the readme I'll merge it.

**Comment by Roboe** [comment]
Gràcies, Jaume! :+1:
